### ISSUE TITLE
present issues on iOS 13 

### ISSUE THREAD

**Issue by iMostafaSh** [zvonicek/ImageSlideshow#354]
Hello, 

problem in present view controller, and when dismiss view controller that show black screen

**Comment by freeworld1995** [comment]
mine is showing white screen after dismiss the fullscreen viewController

**Comment by zvonicek** [comment]
Hi, can you reproduce this in the example project? Any way to see this on my side would help me with fixing that.

**Comment by freeworld1995** [comment]
I update to latest version 1.8.1 (I was using 1.8.0 before) and the problem was fixed on IOS 13. @MustafaPro maybe you should update too
@zvonicek thank you for the quick response

**Comment by Yarob50** [comment]
I updated to 1.8.1 but the issue is still there,
any help will be appreciated

**Comment by primeviltom** [comment]
G'day guys, 

I too have run into the same fullscreen issue on iOS 13 / (13.1.2 on device, 13.0 in simulator), Running ImageSlideShow 1.8.1.... Here's some screenshots of the simulator.. fullscreen just shows the top of the navigation bar, and closing just gives me a black screen.. same issue on a physical device... https://imgur.com/a/RNAys8p

**Comment by redisky** [comment]
ImageSlideShow 1.8.1 
On a physical device iphone 7 iOS 13.1.2:
1) opens in fullscreen
2) then shift the view down a few points (15-20)
3) on dismiss action again fullscreen

On simulator is fine
[https://yadi.sk/i/0r23Pb1P6LYbuw](url)

**Comment by matthew-niemann** [comment]
ImageSlideShow 1.8.1, iOS 13.1 Simulator 

I can confirm that the issue lies somewhere in the `ZoomAnimatedTransitioningDelegate`.
If you manually create and present a `FullScreenSlideshowViewController` without a transition delegate, you can dismiss it without any issues.

**Comment by rashidramazanov** [comment]
A workaround while waiting for fix. Call this function by checking #if available(iOS 13.0, *)

`
extension ImageSlideshow {
    
    @discardableResult
    open func presentFullScreenControllerForIos13(from controller: UIViewController) -> FullScreenSlideshowViewController {
        let fullscreen = FullScreenSlideshowViewController()
        fullscreen.pageSelected = {[weak self] (page: Int) in
            self?.setCurrentPage(page, animated: false)
        }

        fullscreen.initialPage = currentPage
        fullscreen.inputs = images
        // slideshowTransitioningDelegate = ZoomAnimatedTransitioningDelegate(slideshowView: self, slideshowController: fullscreen)
        fullscreen.transitioningDelegate = slideshowTransitioningDelegate
        fullscreen.modalPresentationStyle = .fullScreen
        controller.present(fullscreen, animated: true, completion: nil)

        return fullscreen
    }
    
}
`

**Comment by JoaoMartins1930** [comment]
How can I update ImageSlideShow?

**Comment by Vaishali-PeCfy** [comment]
Hello,

problem in present view controller, and when dismiss view controller that show black screen.. any got the solution ?? Please let me know..

**Comment by JoaoMartins1930** [comment]
> 
> 
> Hello,
> 
> problem in present view controller, and when dismiss view controller that show black screen.. any got the solution ?? Please let me know..

Just update de ImageSlideShow to the latest version

**Comment by rupaksp** [comment]
Any update ?

**Comment by zvonicek** [comment]
I can't reproduce the issue on 1.8.1 anymore. Does anyone still have problems with this?

**Comment by MickaelLEBRET** [comment]
I confirm there is no issue anymore with 1.8.1 on iPhone 8+ (iOS 13) and iPad Pro 12,9 (iOS 13, simulator) for me !

**Comment by zvonicek** [comment]
Should be fixed in version 1.9.0. Let me know if it works properly now and reopen the ticket if not.
